<?php

/**
 * @file
 * Crescent base functionality
 */

module_load_include("inc", "crescent_base", "includes/crescent_base.blocks");

/**
 * Implements hook_menu().
 */
function crescent_base_menu() {
  $items = array();

  $items['admin/config/crescent-base'] = array(
    'title' => t('Crescent consulting'),
    'position' => 'right',
    'weight' => -5,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $items['admin/config/crescent-base/settings'] = array(
    'title' => t('Crescent consulting Settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('crescent_base_admin_settings'),
    'access arguments' => array('access to crescent base settings'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'crescent_base.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function crescent_base_theme() {
  $module_path = drupal_get_path('module', 'crescent_base');
  $base = array(
    'path' => $module_path . "/templates",
  );

  return array(
    'crescent_base_enviro_edge_block' => $base + array(
      'variables' => array(
        'block' => NULL,
      ),
      'template' => 'blocks/crescent_base_enviro_edge_block',
    ),
    'crescent_base_qt_quicktabs_tabset' => array(
      'render element' => 'tabset',
    ),
  );
}

/**
 * Implements hook_admin_menu_output_alter().
 */
function crescent_base_admin_menu_output_alter(&$content) {
  if (user_access('edit any management_team content') && isset($content['menu']['node/add'])) {
    $team_member = array(
      '#title' => t('Add Team Member'),
      '#href' => 'field-collection/field-mt-items/add/node/18',
      '#options' => array(
        'query' => array('destination'=>'node/19?qt=1'),
      ),
    );
    $content['menu']['node/add']['node/add/custom-team-member'] = $team_member;
  }
}

/**
 * Theme function to output tablinks for classic Quicktabs style tabs.
 *
 * @ingroup themeable
 */
function theme_crescent_base_qt_quicktabs_tabset($vars) {
  $variables = array(
    'attributes' => array(
      'class' => 'quicktabs-tabs quicktabs-style-' . $vars['tabset']['#options']['style'],
    ),
    'items' => array(),
  );
  foreach (element_children($vars['tabset']['tablinks']) as $key) {
    $item = array();
    if (is_array($vars['tabset']['tablinks'][$key])) {
      $tab = $vars['tabset']['tablinks'][$key];
      if ($key == $vars['tabset']['#options']['active']) {
        $item['class'] = array('active');
      }
      $item['data'] = drupal_render($tab);
      $variables['items'][] = $item;
    }
  }
  return '<div class="b-tabs-wrapper">' . theme('item_list', $variables) . '</div>';
}