<footer id="site-footer" class="site-footer">
  <div class="container">
    <div class="logo">
      <a href=""><img src="theme/images/logo-s.png" alt=""/></a>
    </div>
    <span>© Crescent Consulting. All rights reserved.</span>

    <div class="region region-footer">
      <ul class="menu">
        <li class="expanded"><a href="">About </a>
          <ul class="menu">
            <li><a href="">Test</a></li>
          </ul>
        </li>
        <li><a href=""> Careers </a></li>
        <li><a href=""> Contact Us</a></li>
      </ul>
    </div>
  </div>
</footer>