<header id="site-header" class="site-header">
  <div class="container">
    <div class="logo">
      <a href="#"><img src="theme/images/logo.png" alt=""/></a>
    </div>

    <a href="" class="btn-mobile"><span></span></a>

    <div class="right-part">
      <nav class="nav">


        <div class="menu-block-wrapper">
          <ul class="menu">
            <li class="expanded"><a href="#"> About </a>

              <div class="sublevel">
                <ul class="menu">
                  <li><a href="">test test test</a></li>
                  <li><a href="">test test test</a></li>
                </ul>
              </div>
            </li>

            <li><a href="#"> Consultants / Solutions </a></li>
            <li><a href="#"> Customers </a></li>
            <li><a href="#"> Careers </a></li>
            <li><a href="#"> Contact Us </a></li>
          </ul>
        </div>
      </nav>
      <!--      <div class="login-btn"><a href="#" class="btn">EnviroEdge</a></div>-->
    </div>
  </div>
</header>